### ISSUE TITLE
Error TS2694 when building app on Angular 11

### ISSUE THREAD

**Issue by mtakemoto** [Arnaud73/ngx-matomo#54]
After getting the 0.1.4 version to work in my app, I tried upgrading to 1.0.0-rc.1 and the build failed.  Found it weird that 0.1.4 worked and this didn't so I figured it's time to ask for help.  Any thoughts on the error below?  Pasted my env too.  I've tried:

1. Cleaning/reinstalling `node_modules`
2. Removing references to injector from my code

Found some other GitHub threads that have a similar error
https://github.com/angular/angular/issues/35291#issuecomment-585102857
https://github.com/sclausen/ngx-mqtt/issues/137

```
Error: node_modules/ngx-matomo/lib/matomo-injector.service.d.ts:19:21 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

19     static ɵfac: i0.ɵɵFactoryDeclaration<MatomoInjector, never>;
                       ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-matomo/lib/matomo-injector.service.d.ts:20:22 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

20     static ɵprov: i0.ɵɵInjectableDeclaration<MatomoInjector>;
                        ~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-matomo/lib/matomo-route-tracker.service.d.ts:48:21 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

48     static ɵfac: i0.ɵɵFactoryDeclaration<MatomoRouteTracker, never>;
                       ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-matomo/lib/matomo-route-tracker.service.d.ts:49:22 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

49     static ɵprov: i0.ɵɵInjectableDeclaration<MatomoRouteTracker>;
                        ~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-matomo/lib/matomo-tracker.service.d.ts:709:21 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

709     static ɵfac: i0.ɵɵFactoryDeclaration<MatomoTracker, never>;
                        ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-matomo/lib/matomo-tracker.service.d.ts:710:22 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

710     static ɵprov: i0.ɵɵInjectableDeclaration<MatomoTracker>;
                         ~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-matomo/lib/matomo.module.d.ts:27:21 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 
'ɵɵFactoryDeclaration'.

27     static ɵfac: i0.ɵɵFactoryDeclaration<MatomoModule, never>;
                       ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-matomo/lib/matomo.module.d.ts:28:21 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 
'ɵɵNgModuleDeclaration'.

28     static ɵmod: i0.ɵɵNgModuleDeclaration<MatomoModule, never, never, never>;
                       ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-matomo/lib/matomo.module.d.ts:29:21 - error TS2694: Namespace '"[AppPath]/src/angular-app/node_modules/@angular/core/core"' has no exported member 
'ɵɵInjectorDeclaration'.

29     static ɵinj: i0.ɵɵInjectorDeclaration<MatomoModule>;
                       ~~~~~~~~~~~~~~~~~~~~~


Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 131:10-28
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2054:10-28
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2231:10-28
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2335:10-28[0m
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 139:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2062:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2239:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2351:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 123:22-43
"export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2046:21-42
"export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2217:26-47
"export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2321:20-41
"export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 133:23-479m
"export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2056:22-46
"export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2233:27-51
"export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2343:20-42
"export 'ɵɵngDeclareInjector' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ngx-matomo/fesm2015/ngx-matomo.js 2337:20-42
"export 'ɵɵngDeclareNgModule' (imported as 'i0') was not found in '@angular/core'
```

Environment
```
ng v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.4
Node: 12.18.3
OS: win32 x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.3
typescript                      4.1.5
```

Thanks!

**Comment by Arnaud73** [comment]
Thank you for giving a try to the RC version :)

Regarding your issue, I would try:
* First, remove node_modules + package-lock.json / yarn.lock ; reinstall and then rebuild your app.
* Or, if the previous idea fails, replace ngx-matomo with the 1.0.0-rc.0 release which was built with Angular 11.2 (instead of 12 RC).

Let me know. If you still can not make it run, simplify your app so that it's almost empty (and reproduces the problem) and send it to me, I'll have a look.

**Comment by mtakemoto** [comment]
Using 1.0.0-rc.0 fixed it!  Thanks for helping me out so quickly.  I'm good with using rc.0 for now, but if you need any other info to fix it for 1.0 just let me know.

**Comment by Arnaud73** [comment]
It seems that this Angular 12 lib is only going to work for Angular 12+ apps.
I guess I'm going to have to publish one 1.0 lib for Angular 9 to 11, and one 2.0 for Angular 12+.

I'll let you know, I'm going to port it on Angular 9 and test it with Angular 9, 10 and 11.

**Comment by fredericg78** [comment]
> Using 1.0.0-rc.0 fixed it! Thanks for helping me out so quickly. I'm good with using rc.0 for now, but if you need any other info to fix it for 1.0 just let me know.

Not for me, issue remains with angular 11 whatever the version.

**Comment by Arnaud73** [comment]
> > Using 1.0.0-rc.0 fixed it! Thanks for helping me out so quickly. I'm good with using rc.0 for now, but if you need any other info to fix it for 1.0 just let me know.
> 
> Not for me, issue remains with angular 11 whatever the version.

It's very curious to have this message if not using a library built with and for Angular 12.

@fredericg78, can you give me your Angular configuration?

**Comment by fredericg78** [comment]
Here is the angular config:
{
  "name": "productName",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc",
    "post-build": "node ./post-build.js"
  },
  "private": true,
  "dependencies": {
    "@angular-material-components/datetime-picker": "^5.1.0",
    "@angular-material-components/moment-adapter": "^5.0.0",
    "@angular/animations": "^11.2.13",
    "@angular/cdk": "^11.2.12",
    "@angular/common": "^11.2.13",
    "@angular/compiler": "^11.2.13",
    "@angular/core": "^11.2.13",
    "@angular/forms": "^11.2.13",
    "@angular/localize": "^11.2.13",
    "@angular/material": "^11.2.12",
    "@angular/material-moment-adapter": "^11.2.12",
    "@angular/platform-browser": "^11.2.13",
    "@angular/platform-browser-dynamic": "^11.2.13",
    "@angular/platform-server": "^11.2.13",
    "@angular/router": "^11.2.13",
    "@auth0/angular-jwt": "^5.0.2",
    "@ng-bootstrap/ng-bootstrap": "^9.1.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@popperjs/core": "^2.9.2",
    "@swimlane/ngx-charts": "^17.0.1",
    "@types/d3": "^6.3.0",
    "ajv": "^8.3.0",
    "ajv-keywords": "^5.0.0",
    "angular-gauge": "^4.0.0",
    "boosted": "^4.6.0",
    "bootstrap": "^4.6.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^3.11.1",
    "file-saver": "^2.0.5",
    "focus-visible": "^5.2.0",
    "install": "^0.13.0",
    "moment": "^2.29.1",
    "ng-drag-drop": "^5.0.0",
    "ngx-cookie-service": "^11.0.2",
    "ngx-matomo": "^1.0.0-rc.0",
    "ngx-order-pipe": "^2.1.1",
    "ngx-pagination": "^5.1.0",
    "ngx-permissions": "^8.1.1",
    "ngx-quicklink": "^0.2.7",
    "npm": "^6.14.13",
    "popper.js": "^1.16.1",
    "rxjs": "^6.6.7",
    "sse.js": "^0.5.0",
    "swiper": "^4.5.1",
    "tablesorter": "^2.31.3",
    "web-animations-js": "^2.3.2",
    "zone.js": "^0.11.4"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "~8.4.1",
    "@angular-devkit/build-angular": "^0.1102.12",
    "@angular-eslint/builder": "4.2.1",
    "@angular-eslint/eslint-plugin": "4.2.1",
    "@angular-eslint/eslint-plugin-template": "4.2.1",
    "@angular-eslint/schematics": "4.2.1",
    "@angular-eslint/template-parser": "4.2.1",
    "@angular/cli": "^11.2.12",
    "@angular/compiler-cli": "^11.2.13",
    "@angular/language-service": "^11.2.13",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^14.14.43",
    "@typescript-eslint/eslint-plugin": "4.23.0",
    "@typescript-eslint/parser": "4.23.0",
    "eslint": "^7.26.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "34.0.2",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "^8.10.2",
    "tslib": "^2.2.0",
    "typescript": "4.0.7",
    "webpack": "^4.6.0",
    "webpack-cli": "^4.6.0"
  },
  "peerDependencies": {
    "tslib": "^2.2.0"
  }
}

**Comment by Arnaud73** [comment]
I guess your problem comes from `"ngx-matomo": "^1.0.0-rc.0"` which would resolve to the rc.1 package instead.

Please try `"ngx-matomo": "1.0.0-rc.0"` instead

**Comment by Arnaud73** [comment]
I started working on release 1.0 almost 2 years ago, but I could not finish as soon as I wished. As a result I left the repo with half the work done, so many, rightfully, decided to fork it and produce their own flavor. ngx-matomo-revived is one of them, I'll have a look at all of them to get some inspiration for some missing features :)
